project:
  type: website

website:
  title: "Siple projects"
  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    css: styles.css
   


