---
title: "Margaret Siple's quarto page"
---

# About

Welcome to my Quarto webpage! I am a Research Fish Biologist at NOAA's Alaska Fisheries Science Center, in the Groundfish Assessment Program. I built this page to host teaching and research materials that others may need easy access to. It is very much a work in progress.

The page is public. The source code for this website is [here](https://github.com/MargaretSiple-NOAA/siple-quarto). 

# Research

In GAP, I work on the development of indices of abundance for stock assessment, and on improving Essential Fish Habitat information for groundfish and invertebrates in Alaska fisheries.

## Postdoctoral projects

### Marine mammal bycatch
A collaborative project led by the Ocean Modeling Forum at the University of Washington. More info [here](currentprojects/bycatch.qmd).

### The value of ecological information
A James S. McDonnell Fellowship project at the University of California, Santa Barbara.

### Forage species ecology and management
My dissertation topic, but also an ongoing area of exploration. I am interested in how we can better incorporate ecological information (environmental data, predation information, and more) into the models we use for managing forage species.

# Teaching
Materials for teaching about data visualization, Shiny, marine ecology, and fisheries management are slowly being assembled in the [Teaching](teaching.qmd) page.



---
I learned how to use Quarto from Openscapes and R-Ladies Santa Barbara.
