---
title: "Marine mammal bycatch"
format: html
---

## Background

This project is supported by the [Ocean Modeling Forum](https://oceanmodelingforum.org/) and the [Lenfest Ocean Program](https://www.lenfestocean.org/en). The goal of the project was to provide a toolbox of tools helpful for stakeholders with data-poor marine mammal stocks. 

The Marine Mammal Bycatch Working Group is a collaboration between academics and scientists from inside and outside NOAA. My primary contribution to this project was the `{mmrefpoints}` R package and Shiny app. I contributed to this work as a postdoctoral research associate at the University of Washington.

Below you will find links to code, tutorials, and talks about the R package and Shiny app.

## R package

The `{mmrefpoints}` [R package](https://github.com/mcsiple/mmrefpoints) provides tools for projecting marine mammal abundance under different bycatch scenarios. It can also be used as a way to access the Shiny app offline.

The code for `{mmrefpoints}` is open source and published in the [Journal of Open Source Software](https://joss.theoj.org/papers/10.21105/joss.03888).

## Shiny app

The MMBIET Shiny app, included in `{mmrefpoints}` is available [here](https://msiple.shinyapps.io/mmrefpoints/). If you have any trouble with the app or want to request a new feature, visit the [Issues page](https://github.com/mcsiple/mmrefpoints/issues) for the package. 

## Talks

Material from this project has been presented at workshops and in lectures. 

* **Webinar: Best practices to assess and manage marine mammal bycatch**. Lenfest Ocean Program, March 14, 2022. ([link](https://www.youtube.com/watch?v=JMX_fggxpw4) - app introduction starts at 34:15)

* **A tool for projecting marine mammal abundance under different bycatch scenarios**. January 7, 2022. University of Washington Quantitative Seminar. ([link](https://www.youtube.com/watch?v=LO_HsO4fVy8))


## Papers

Siple et al. 2022. [`mmrefpoints`: Projecting long-term marine mammal abundance with bycatch](https://joss.theoj.org/papers/10.21105/joss.03888). *Open access*.

See the Ocean Modeling Forum [website](https://oceanmodelingforum.org/working-groups/marine-mammal-bycatch-working-group/) for a full list of paper from the Marine Mammal Bycatch Working Group.

